name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - run: npm install

      # 4️⃣ Build Vite project
      - run: npm run build

      # 5️⃣ Deploy /dist folder to GitHub Pages
      - uses: actions/deploy-pages@v4
        with:
          path: ./dist

  # Optional: automatically remove old files
  clean:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Cleanup done"
